name: "Convert TODO to issues"
on:
    push:
        branches:
        - main
        - 'dev/**'
jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@master"
            - name: "Convert TODO to GitHub Issue"
                uses: "alstr/todo-to-issue-action@v4.1.1"
                id: "todo"